# Generated by Django 4.2.7 on 2023-11-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategysteps',
            old_name='name',
            new_name='description',
        ),
    ]
